from django.urls import path
from .views import (
    HomeView,
    landing_page,
    change_password,
    password_change_done,
    login,
    signup,
    notification,
    FAQ,
    transaction,
    marketplace,
    market,
    initiate_payment,
    kyc,
    courses,
    courseregistrationform,
    adminpage,
    available_courses,
    upload_course,
    register_course,
    registration_success,
    user_profile,
    registration_history,
    get_private_key,
    allreg,
    logout_view,
    sa,
    shared_apartment,
    apartment_detail,
    pet_friendlyapa, 
    near_library,
    search_apartments,
    application,
    applications,
    apply_for_apartment,
    reply_to_application,
    inbox,
    get_secret_key,
)

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', HomeView.as_view(), name='home'),
    path('login/', login, name='login'),
    path('signup/', signup, name='signup'),
    path('change_password/', change_password, name='change_password'),
    path('password_change_done/', password_change_done, name='password_change_done'),
    path('notification/', notification, name='notification'),
    path('FAQ/', FAQ, name='FAQ'),
    path('transaction/', transaction, name='transaction'),
    path('marketplace/', marketplace, name='marketplace'),
    path('market/', market, name='market'),
    path('initiate_payment/', initiate_payment, name='initiate_payment'),
    path('kyc/', kyc, name='kyc'),
    path('courses/', courses, name='courses'),
    path('courseregistrationform/', courseregistrationform, name='courseregistrationform'),
    path('adminpage/', adminpage, name='adminpage'),
    path('admin/upload-course/', upload_course, name='upload_course'),
    path('student/available-courses/', available_courses, name='available_courses'),
    path('register-course/<int:course_id>/', register_course, name='register_course'),
    path('registration-success/', registration_success, name='registration_success'),
    path('profile/', user_profile, name='user_profile'),
    path('registration-history/', registration_history, name='registration_history'),
    path('allreg/', allreg, name='allreg'),
    path('get-private-key/', get_private_key, name='get_private_key'),
    path('logout/', logout_view, name='logout'),
    path('shared_apartment/', shared_apartment, name='shared_apartment'),  # Shared apartments view
    path('apartment/<int:apartment_id>/', apartment_detail, name='apartment_detail'),
    path('hostelallocation/apartment/<int:apartment_id>/', apartment_detail, name='apartment_detail'),
    path('pet_friendlyapa/', pet_friendlyapa, name='pet_friendlyapa'), 
    path('near_library/', near_library, name='near_library'),
    path('ajax/search-apartments/', search_apartments, name='search_apartments'),
    path('application/', application, name='application'),
    path('applications/', applications, name='applications'),
    path('apply/', apply_for_apartment, name='apply_for_apartment'),
    path('reply/<int:application_id>/', reply_to_application, name='reply_to_application'),
    path('inbox/', inbox, name='inbox'),
    path('sa/', sa, name='sa'),
    path('api/secret-key/', get_secret_key, name='get_secret_key'),
]   
   