# Generated by Django 5.1 on 2025-06-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemanagementsystem', '0002_classsession_remove_message_apartment_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('mc', 'Mass Communication'), ('journalism', 'Journalism'), ('eee', 'Electrical Electronics Engineering'), ('ba', 'Business Administration'), ('se', 'Software Engineering')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
