# Generated by Django 5.1 on 2025-06-30 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemanagementsystem', '0004_classsession_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
