# Generated by Django 5.1 on 2025-06-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemanagementsystem', '0005_classsession_attendance_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='attendance_token',
        ),
    ]
