# Generated by Django 5.2.5 on 2025-09-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemanagementsystem', '0008_usersubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
